package Redux2;

public enum ItemType {
    DISPENCER, FOOD, TOY, TEST, KEY, CLOTHING, SEAT, UNREMOVABLE, DRINK, PARKOURABLE, CONTAINER,LITTER, EDUCAITONAL, SHARP, SHOP, TRADER, INTERACTABLE, PAW, EQUIPMENT, STORAGE, CRAFTING, SUPPLIES, 
    STATIONARY, TOOL, SCIENCE, EDUCATIONAL, TECH, ENTERTAINMENT, FURNITURE, 
    COMMUNICATION, SOCIAL, MUSIC, EXPLORATION, COOKING, TRASH, BOOK, UNDERPANTS, 
    TOP, BOTTOM, HAT, SHOES, BACKPACK, DIAPER, SOCKS, DROPPABLE, TAKEABLE,CONTRABAND,
}
