package Redux2;

public enum Proficiencies {
    DRESS,BATHE,BRUSH,READ,WRITE,READALOUD,PLAY,LISTEN,SMELL,STANDUP,STAND_ON,JUMP, OFF,CLIMB,SWIM,FLY,DRIVE,OPEN,LOCK,UNLOCK,REMOVE,PAYATTENTION, DRAW, CRAFT, RUN, PRETEND, PERFORM, EMPATHIZE, EXPRESS, SPEAK, BEFRIEND, SHARE, SIMPLE_INSTRUCTIONS, PARALLEL_PLAY, CRAWL, EXPRESS_DISTRESS, NAP, EAT_HELPED, SOLVE, MEMORIZE, DIRECT, CREATE, SOOTHE_SELF, EXPRESS_NEEDS, BATHE_SELF, BRUSH_SELF, SOLVE_MEDIUM, COMPLEX_INSTRUCTIONS, PUBLIC_SPEAK, LEADER, CLIQUE, DRAW_WELL, CRAFT_LVL2, BRAVO, COSTUMEDESIGN, TUTOR, WRITE_WELL, SOOTH_OTHERS, SHARE_LVL2, DRESS_SELF, KEEP_CLEAN, SOLVE_COMPLEX, MEMORIZE_MORE, SPEAK_CLEARLY, LISTEN_CAREFULLY, POPULAR, CHARISMATIC, DRAW_EXPERT, CRAFT_LVL3, BALANCE, DODGE, LISTEN_CAREFULLY_LVL2, FOLLOW_CONVERSATION, MEMORIZE_EXPERT, SOLVE_EXPERT, KEEP_CLEAN_LVL2, DRESS_WELL, SHARE_LVL3, SOOTH_LVL2, WRITE_EXPERT, TUTOR_LVL2, CREATE_LVL2, DIRECT_LVL2, TODDLE, WALK;

    String getName() {
        return GameHandler.toSentenceCase(this.name());
    }
}
