package Redux2;

public enum PawsAbility {
    // Abilities
    // Common
    BITE, SCRATCH, HISS, GROWL, POUNCE, LICK,EVASION,HEAVY_HIT,HEALING_WIND, SNEAK,CONFUSION,DEFENCE, STARE, SPY, TRAIN, STUDY, SUPPORT, EMPOWER, STRENGTHEN, ENHANCE, TRANSFORM, FLOW, BEAM, SPEED,CRITICAL
    // Uncommon

}
